# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [ "btrfs" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f1401ad9-593e-4a30-af9b-cfd1d885ba43";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd:7" "noatime"];
    };

  boot.initrd.luks.devices."enc".device = "/dev/disk/by-uuid/46b2c63c-46cc-49d5-b722-fcc4cf3c2bc2";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/f1401ad9-593e-4a30-af9b-cfd1d885ba43";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd:7" "noatime"];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/f1401ad9-593e-4a30-af9b-cfd1d885ba43";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd:7" "noatime"];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/f1401ad9-593e-4a30-af9b-cfd1d885ba43";
      fsType = "btrfs";
      options = [ "subvol=log" "compress=zstd:7" "noatime"];
      neededForBoot = true;
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E768-0FDC";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
